### ISSUE TITLE
failed for back view

### ISSUE THREAD

**Issue by KeruZheng** [pcr-upm/opal23_headpose#10]
![image](https://github.com/user-attachments/assets/f57f7f47-ae11-4ee2-ae75-898fed3d97f3)
![3e2a52aa35a6df2ffea73447804c379](https://github.com/user-attachments/assets/81cc8e4d-e6a3-4120-a573-118bb812ec13)

Good evening to the authors! Recently I found that the model failed on the back view picture but performed well in the front view and side view. I wonder if I missed some step?  I tried 300wlp and 300wlp_euler, they got the same results. I really appreciate your help! Thanks a looooooooooooot!

**Comment by alejandro-cobo** [comment]
Hello, thanks for your interest in our work.
Since 300W-LP is a short-range head pose estimation dataset, models trained on it can only estimate up to [-90º, 90º] yaw rotations.
For back view images, you should use the models trained on CMU Panoptic dataset. However, keep in mind that this dataset does not include in-the-wild images, and generalization is limited.
It is also important to check the bounding boxes you are using, as most face detectors only work with frontal views.

**Comment by KeruZheng** [comment]
thanks for your reply! I will try it around this week and update.
