### ISSUE TITLE
How to get headpose labels

### ISSUE THREAD

**Issue by birdflies** [pcr-upm/opal23_headpose#8]
Good Jobs，Would  you like to share how to obtain the label file for headpose of panoptic. Looking forward to your reply. Thanks

**Comment by alejandro-cobo** [comment]
Hello, the head pose labels for CMU Panoptic dataset were obtained using the code from WHENet: https://github.com/Ascend-Research/HeadPoseEstimation-WHENet
For each video, we select one frame out of every 30, and only save samples were the 31 points of view can be annotated.
Since we also removed faulty images and manually refined a big part of the dataset, it would be impossible for us to provide a single script to replicate the text files.
If you have any further questions, feel free to ask anytime.

**Comment by birdflies** [comment]
Thanks~
